### ISSUE TITLE
Pip installation fails on M1 Mac

### ISSUE THREAD

**Issue by ArniDagur** [ArniDagur/python-adblock#38]
Note to self, investigate the following;
```
username@hostname ~ % pip3 install adblock
Collecting adblock
  Downloading https://files.pythonhosted.org/packages/c3/2f/eff1d8621725d15ea3d353957234db99be948f49b282b22aa4d17c45cf95/adblock-0.4.2.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: adblock
  Building wheel for adblock (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /Library/Developer/CommandLineTools/usr/bin/python3 /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /var/folders/g5/bzl0cc7j7dvg00rggnfl0jzc0000gn/T/tmps65nnwtz
       cwd: /private/var/folders/g5/bzl0cc7j7dvg00rggnfl0jzc0000gn/T/pip-install-aoc7i7qz/adblock
  Complete output (11 lines):
  Running `maturin pep517 build-wheel -i python`
  Traceback (most recent call last):
    File "<string>", line 19, in <module>
  AttributeError: 'module' object has no attribute 'base_prefix'
  💥 maturin failed
    Caused by: The given list of python interpreters is invalid
    Caused by: python is not a valid python interpreter
    Caused by: Trying to get metadata from the python interpreter 'python' failed
  🍹 Building a mixed python/rust project
  🔗 Found pyo3 bindings
  Error: command ['maturin', 'pep517', 'build-wheel', '-i', 'python'] returned non-zero exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for adblock
  Running setup.py clean for adblock
  ERROR: Command errored out with exit status 1:
   command: /Library/Developer/CommandLineTools/usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/g5/bzl0cc7j7dvg00rggnfl0jzc0000gn/T/pip-install-aoc7i7qz/adblock/setup.py'"'"'; __file__='"'"'/private/var/folders/g5/bzl0cc7j7dvg00rggnfl0jzc0000gn/T/pip-install-aoc7i7qz/adblock/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: /private/var/folders/g5/bzl0cc7j7dvg00rggnfl0jzc0000gn/T/pip-install-aoc7i7qz/adblock
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/tokenize.py", line 392, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/g5/bzl0cc7j7dvg00rggnfl0jzc0000gn/T/pip-install-aoc7i7qz/adblock/setup.py'
  ----------------------------------------
  ERROR: Failed cleaning build dir for adblock
Failed to build adblock
ERROR: Could not build wheels for adblock which use PEP 517 and cannot be installed directly
WARNING: You are using pip version 19.2.3, however version 21.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
Possibly related to https://github.com/PyO3/maturin/pull/471

**Comment by messense** [comment]
You can built universal2 wheels with maturin. I usually do it like this: https://github.com/messense/rjieba-py/blob/7326354f8e7dbc9131c6199a367d44126c9c6d7e/.github/workflows/CI.yml , it has builds for x86_64/aarch64 macOS wheels, x86_64/i686 Windows wheels and x86_64/i686/aarch64/armv7l manylinux wheels.

**Comment by ArniDagur** [comment]
Wow! That will be useful, thanks. Question: It appears that you only make wheels for Python version `3.6`. Is there anything preventing me from building for all of `(3.6, 3.7, 3.8, 3.9)`?

**Comment by messense** [comment]
It builds abi3 wheels which supports Python 3.6 and later with only a single wheel.

https://pyo3.rs/v0.13.2/building_and_distribution.html#py_limited_apiabi3

**Comment by messense** [comment]
> Wow! That will be useful, thanks. Question: It appears that you only make wheels for Python version `3.6`. Is there anything preventing me from building for all of `(3.6, 3.7, 3.8, 3.9)`?

You can also checkout how cramjam does it https://github.com/milesgranger/pyrus-cramjam/blob/master/.github/workflows/CI.yml

**Comment by ArniDagur** [comment]
Thanks to @messense, installation now works fine.

```
[arni][/Users/arni]% pip3 install adblock                    
Collecting adblock
  Downloading adblock-0.4.4-cp36-abi3-macosx_10_9_universal2.whl (3.1 MB)
     |████████████████████████████████| 3.1 MB 1.2 MB/s 
Installing collected packages: adblock
Successfully installed adblock-0.4.4
[arni][/Users/arni]% python3 -c "import adblock; print(adblock.__version__)"
0.4.4
[arni][/Users/arni]% python3 --version                                      
Python 3.9.4
```
